name: Print To-Do List

on: 
    push:
        branches:
            -main
    workflow_dispatch:

jobs:
    print:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - run: cat Todolist.txt
